micronaut:
  application:
    name: brokenquery
datasources:
  default:
    url: jdbc:postgresql://localhost:5432/postgres
    driverClassName: org.postgresql.Driver
    username: postgres
    password: ''
    schema-generate: CREATE_DROP
    dialect: POSTGRES
netty:
  default:
    allocator:
      max-order: 3
---
#arbitrary value with mixture of alphanum + symbols
query-value: dfyui123456!@#$%^&*(),.?><asdRGFf
